name: Docker CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -f Dockerfile --tag registry.sbx320.net/rd2l/inhouse:latest
    - name: Docker Push
      run: docker push registry.sbx320.net/rd2l/inhouse:latest
